### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rmehta** [frappe/esoc-18#2]
Every participant must select a module

### CRM

- [ ] feature spec
- [ ] models (Customer, Lead, Opportunity)

### Inventory
  - [ ] Warehouse Tree
  - [ ] Serial Number
  - [ ] Batch Number
  - [ ] QR Code Scanning
  - [ ] Stock Movement (items, from, to)
  - [ ] Reports (balance, ledger)

### Accounting
  - [ ] Financial Reporting
  - [ ] GST Reports (India)
  - [ ] Dashboards

### Point of Sale
 - [ ] Setup
 - [ ] Selection View (Scan / pick items)
 - [ ] Customer Creation
 - [ ] Billing Summary
 - [ ] Payment (change)
 - [ ] Bill Printing (email)

### Email
  - [ ] Email Account
  - [ ] Contact
  - [ ] Email Group (group of contacts)
  - [ ] Email
  - [ ] Attachment
  - [ ] Sending (SMTP)
  - [ ] Receiving (IMAP)
  - [ ] Viewing
  - [ ] Threading
  - [ ] Timeline view

### Notifications
  - [ ] Notification Rule
  - [ ] Alert Rule

### Other
- [ ] SMS Sending
- [ ] Contact Sync
- [ ] QR Code Scanning

### Report Builder

- [ ] Pick Columns
- [ ] Filters
- [ ] Chart Setup
- [ ] Preset reports

### Calendar View

- [ ] View
- [ ] Event mapping

## Backend + Network

- [ ] Convert to Server
- [ ] Authentication
- [ ] Data-sync (outgoing and incoming queue)
- [ ] Database migration
- [ ] Peer-to-peer (WebRTC)
- [ ] STUN + TURN Server Setup

**Comment by netchampfaris** [comment]
## Mobile App Architecture

- [ ] Offline first
- [ ] Data should be stored in the local db first with a local ID
- [ ] On network connection, it should sync in the background and it's ID should be set from the remote server.
- [ ] Implementation can be done using a Queue which maintains list of unsynced records.

**Comment by accakks** [comment]
Hi, I'm interested to work on email part in utilities.

**Comment by shailysangwan** [comment]
I'd like to work on setting up the backend.

**Comment by krishamehta** [comment]
I would like to work on accounting

**Comment by anto-christo** [comment]
I'd like to take Point of Sale, anyone else interested?

**Comment by Jap-Leen** [comment]
I would like to work on report builder and calendar view.

**Comment by sayantikabanik** [comment]
would like to take up inventory

**Comment by haquezameer** [comment]
I would like to work on desktop module.

**Comment by DanCarl857** [comment]
I will like to work on the mobile app

**Comment by meets2tarun** [comment]
I'd like to work on email part.

**Comment by jaffreyjoy** [comment]
I'd like to work on accounting

**Comment by itzzritik** [comment]
My first preference - Mobile app
Second - Email
I'm comfortable with any of the above.

**Comment by inishchith** [comment]
i'm comfortable working under Desktop Module or Email (under Utilities) .

**Comment by nilshah98** [comment]
I'd like to contribute to Email or Desktop module

**Comment by shivam1708** [comment]
I would like to work under Desktop/email module

**Comment by karan28598** [comment]
I would like to work under inventory or email module. I'm also interested in the Report builder.

**Comment by nurdtechie98** [comment]
I would like to contribute to Point of Sale module or even back-end + networking module.

**Comment by jcs98** [comment]
I would like to work on the point of sale module

**Comment by Parth-Vader** [comment]
I would be happy to work on Backend + Network or the Desktop module.
